# Generated by Django 3.2.8 on 2021-11-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='--Select-one--', max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('speciality', models.CharField(choices=[('Physician', 'Physician'), ('Lab-Assistant', 'Lab-Assistant'), ('Oncologist', 'Oncologist'), ('Cardiologist', 'Cardiologist')], default='--Select-one--', max_length=50)),
                ('Doctoremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorSignup.doctordetail')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.addservice')),
            ],
        ),
    ]
