# Generated by Django 3.2.8 on 2022-02-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorSignup', '0002_auto_20211123_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdata',
            name='FirstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctorsdata',
            name='LastName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='doctorsdata',
            name='address',
            field=models.CharField(max_length=80, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='doctorsdata',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='doctorsdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='--Select-one--', max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='doctorsdata',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='doctorsdata',
            name='speciality',
            field=models.CharField(choices=[('Physician', 'Physician'), ('Lab-Assistant', 'Lab-Assistant'), ('Oncologist', 'Oncologist'), ('Cardiologist', 'Cardiologist')], default='--Select-one--', max_length=50, verbose_name='Speciality'),
        ),
    ]
