# Generated by Django 3.2.8 on 2022-02-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('userSignup', '0004_auto_20211123_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField()),
                ('payment_method', models.CharField(choices=[('E-payment', 'E-payment'), ('Cash', 'Cash')], max_length=120, verbose_name='Payment Method')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.addservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userSignup.userdata')),
            ],
        ),
    ]
