# Generated by Django 3.2.8 on 2022-02-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userSignup', '0004_auto_20211123_2034'),
        ('services', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='payments',
        ),
    ]
