# Generated by Django 3.2.8 on 2022-02-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_payment_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
