# Generated by Django 3.2.8 on 2022-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payments_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(max_length=120, verbose_name='Payment Method'),
        ),
    ]
