# Generated by Django 3.2.8 on 2022-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payments_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='payments',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
