# Generated by Django 3.2.8 on 2022-02-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20220228_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_done',
            field=models.BooleanField(),
        ),
    ]
