# Generated by Django 3.2.8 on 2022-03-18 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorSignup', '0003_auto_20220224_1346'),
        ('notification', '0002_alter_notifydetail_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifydetail',
            name='Doctor_Name',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='doctorSignup.doctorsdata'),
        ),
    ]
