# Generated by Django 3.2.8 on 2021-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSignup', '0002_auto_20211123_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='has_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
