# Generated by Django 3.2.8 on 2021-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSignup', '0003_auto_20211123_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='has_data',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_Verified',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='has_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='is_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
