# Generated by Django 3.2.8 on 2021-11-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('doctorSignup', '0001_initial'),
        ('userSignup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('times', models.TimeField()),
                ('price', models.PositiveSmallIntegerField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorSignup.doctorsdata')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userSignup.userdata')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.addservice')),
            ],
        ),
    ]
