# Generated by Django 3.2.8 on 2022-02-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointdetail_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointdetail',
            old_name='payment_status',
            new_name='payment_done',
        ),
    ]
