# Generated by Django 3.2.8 on 2022-02-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_payment_status_appointdetail_payment_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointdetail',
            name='payment_done',
        ),
    ]
