# Generated by Django 3.2.8 on 2022-03-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorSignup', '0003_auto_20220224_1346'),
        ('medicine', '0002_alter_medicinedetail_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='Doctor_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorSignup.doctorsdata'),
        ),
    ]
